### ISSUE TITLE
VSCode fails to start gluon_language-server

### ISSUE THREAD

**Issue by shingtaklam1324** [gluon-lang/gluon_language-server#21]
Error from Output:

```
[Error - 23:30:17] Starting client failed
Launching server using command gluon_language-server failed.
```

---

`gluon` and `gluon_language-server` are both in `$PATH`, and changing the path to `~/.cargo/bin/gluon_language-server` did not fix the issue.

**Comment by shingtaklam1324** [comment]
I have reinstalled my system on my computer so I won't be able to provide any more information :( . Closing for now.

**Comment by Marwes** [comment]
Let me know if you encounter it again!

**Comment by MarkuBu** [comment]
I have the same issue. 

Ubuntu 20.04, VSCode 1.63.2, rustc 1.58.1

Installed both gluon_repl and language server via cargo install. Both in $PATH (~/.cargo/bin). Can run the repl and language server in a terminal. But when I load a gluon file in VSCode I get this error:

```
[Error - 18:30:02] Starting client failed
Launching server using command gluon_language-server failed.

```
