### ISSUE TITLE
Add a VSCode command to restart the language server

### ISSUE THREAD

**Issue by JameeKim** [gluon-lang/gluon_language-server#28]
I'm compiling a fork of the language server myself every time I add a new type or module to gluon vm for my specific usage. It would be a great help if a way to restart the language server from the extension is added.
I'm using VSCode version 1.30.2 on Ubuntu 18.04LTS.

**Comment by Marwes** [comment]
I think this may need to be part of the client in the editor rather than the server. At least https://github.com/autozimu/LanguageClient-neovim which I use has a command for starting and stopping the server.

Unless you have an idea how this would work on the server side?

**Comment by JameeKim** [comment]
Oh I thought this was also a repository for VSCode extension, because the link to the repository in the extension page led to here. I do not know much about language servers so please bear with me, but the extension is not a kind of client? I'm sorry but I'm confused...

**Comment by Marwes** [comment]
Ah. So there is also a vscode extension in this repo which really should be moved. However, that only covers syntax highlighting and setting up some other configuration.

It could probably add in a keybind to reboot the server though but ideally that should be language agnostic functionality.

Have you looked around for a way to reboot the currently running language server from vs code? It seems plausible that it is something that exists.

**Comment by Marwes** [comment]
Actually, if you force quit the language server with `kill` or a task manager visual studio code will automatically restart it which may be a workaround for what you want

**Comment by JameeKim** [comment]
Thank you for your kind explanation! I'll look into things you suggested. :)
