### ISSUE TITLE
Two different versions of languageserver-types are being installed causing install failure

### ISSUE THREAD

**Issue by tyler-conrad** [gluon-lang/gluon_language-server#30]
Running:

`cargo install gluon_language-server`

results in:

`error: failed to compile `gluon_language-server v0.11.0`

This is caused by 2 different versions of the languageserver-types crate being compiled:

``   --> /home/tyler/.cargo/registry/src/github.com-1ecc6299db9ec823/gluon_language-server-0.11.0/src/command/mod.rs:115:20
    |
115 |             range: byte_span_to_range(source, symbol.span)?,
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `languageserver_types::Range`, found a different struct `languageserver_types::Range`
    |
    = note: expected type `languageserver_types::Range` (struct `languageserver_types::Range`)
               found type `languageserver_types::Range` (struct `languageserver_types::Range`)
note: Perhaps two different versions of crate `languageserver_types` are being used?
``

   Compiling languageserver-types v0.54.0
   Compiling languageserver-types v0.51.1

**Comment by tyler-conrad** [comment]
I was able to work around the issue by cloning the gluon_language-server repo and building that project.  Then specifying the absolute path to the built binary in the settings.json for vscode:

`
{
    "gluon.language-server.path": "/home/tyler/.cargo/bin/gluon_language-server"
}
`

**Comment by Marwes** [comment]
Thanks for reporting! Seems like I need to make another release.
