### ISSUE TITLE
Redundant dependency of debugserver-types

### ISSUE THREAD

**Issue by ndmitchell** [gluon-lang/gluon_language-server#43]
I note that debugserver-types is listed as a dependent package, but I can't see it used anywhere in this repo. Is it a redundant dependency?

The reason I went looking at this package is because it's the only listed reverse dependency of debugserver-types, and I wanted to try out debugserver-types, so was looking for an example :)

**Comment by Marwes** [comment]
There used to be a debugger included which used those types. If you dig around in the git history you should be able to find it though whether it useful for you s anyone's guess

**Comment by ndmitchell** [comment]
For those who come after me, https://github.com/gluon-lang/gluon_language-server/blob/2bc6b4d480fc803046983c20f2fe0d1ac13f3852/src/debugger.rs seems to be an interesting place to start.

Now that debugserver-types is redundant, I'm happy to send a PR removing the dependency, or otherwise I'll just close this issue. Whichever you prefer.

**Comment by Marwes** [comment]
Happy to accept a PR for that! Closing since this is resolved
